# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        uses: subosito/flutter-action@v2.8.0
        with:
          # The Flutter version to make available on the path
          flutter-version: any # optional, default is any
          # The Flutter build release channel
          channel: stable # optional, default is stable
          ## Cache the Flutter SDK
          # cache: # optional
          ## Identifier for the Flutter SDK cache
          # cache-key: # optional, default is flutter-:os:-:channel:-:version:-:arch:-:hash:
          ## Flutter SDK cache path
          # cache-path: # optional, default is ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
          ## The architecture of Flutter SDK executable (x64 or arm64)
          # architecture: # optional, default is ${{ runner.arch }}
